services:

  bili-jean-build:
    build:
      context: .
      target: dev
    image: bili-jean:${IMAGE_TAG:-latest}

  bili-jean-run:
    image: bili-jean:${IMAGE_TAG:-latest}
    volumes:
      - ./:/app/bili-jean/
    command: ["tail", "-f", "/dev/null"]

  bili-jean-lint:
    image: bili-jean:${IMAGE_TAG:-latest}
    command: make lint

  bili-jean-type-hint:
    image: bili-jean:${IMAGE_TAG:-latest}
    command: make type-hint

  bili-jean-test:
    image: bili-jean:${IMAGE_TAG:-latest}
    command: make test
