version: '3.7'

services:

  bili-jean-build:
    build:
      context: .
      target: dev
    image: bili-jean:${IMAGE_TAG:-latest}

  bili-jean-run:
    image: bili-jean:${IMAGE_TAG:-latest}
    volumes:
      - ./:/app/bili-jean/
    ports:
      - "30001:8000"
    command: gunicorn --bind=0.0.0.0:8000 bili_jean.app:app

  bili-jean-test:
    image: bili-jean:${IMAGE_TAG:-latest}
    volumes:
      - ./coverage_report:/app/bili-jean/coverage_report
    command: make test

  bili-jean-lint:
    image: bili-jean:${IMAGE_TAG:-latest}
    command: make lint

  bili-jean-type-hint:
    image: bili-jean:${IMAGE_TAG:-latest}
    command: make type-hint
